#!/bin/bash
#
# Find Top 10 big disk space users in various directories
###########################################################
# Parameters for Script
# echo $1
# 如果后面跟了参数（指定的目录），就统计对应的目录；
# 否则，统计默认的目录
if [ -n "$1" ]
then
	CHECK_DIRECTORIES="$1" 
else
	CHECK_DIRECTORIES="/var/log /home/young" #directories to check
fi

############## Main Script ################################
DATE=$(date '+%m%d%y') # Date for report file

exec > disk_usage_top10_$DATE.rpt # Make report file Std Output

echo "Top 10 Disk Space Usage" # Report header for whole report
echo "for $CHECK_DIRECTORIES Directories"

for DIR_CHECK in $CHECK_DIRECTORIES # Loop to du directories
do
    echo ""
    echo "The $DIR_CHECK Directories:"
    # Create a listing of top ten disk space users
    #### 注意！！！
    # 这里不能为了方便阅读而使用 du -Sh
    # 这样的结果不是我们想要的
    # 因为后面的排序， sort -rn ，-n 表示按数值排序
    # 1M < 1000K （因为 1 < 1000）
    # 这不是我们想要的
    du -S $DIR_CHECK 2>/dev/null | 
    sort -rn |
    sed '{11,$D; =}' |
    sed 'N; s/\n/ /' |
    gawk '{printf $1 ":" "\t" $2 "\t" $3 "\n"}'
done
